version: '3.8'

services:
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'snapp'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - snapp_test
  redis:
    hostname: redis
    image: redis
    ports:
      - '6379:6379'
    networks:
      - snapp_test
volumes:
  my-db:
networks:
  snapp_test:
    driver: bridge
